### ISSUE TITLE
500 issue at https://obscure-eyrie-83404.herokuapp.com/start

### ISSUE THREAD

**Issue by satish603** [satish603/heroku-backend#1]
log file attached 
2021-08-09T05:14:13.896791+00:00 heroku[router]: at=info method=GET path="/start" host=obscure-eyrie-83404.herokuapp.com request_id=6bfef7af-34c0-4ae6-9d80-de15455620aa fwd="106.193.19.5" dyno=web.1 connect=1ms service=23ms status=500 bytes=463 protocol=https
2021-08-09T05:14:13.888776+00:00 app[web.1]: [2021-08-09 05:14:13,888] ERROR in app: Exception on /start [GET]
2021-08-09T05:14:13.888784+00:00 app[web.1]: Traceback (most recent call last):
2021-08-09T05:14:13.888793+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
2021-08-09T05:14:13.888793+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-08-09T05:14:13.888794+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
2021-08-09T05:14:13.888794+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-08-09T05:14:13.888795+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
2021-08-09T05:14:13.888795+00:00 app[web.1]:     rv = self.dispatch_request()
2021-08-09T05:14:13.888796+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
2021-08-09T05:14:13.888796+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-08-09T05:14:13.888796+00:00 app[web.1]:   File "/app/test1.py", line 18, in run_script1
2021-08-09T05:14:13.888797+00:00 app[web.1]:     exec(file)
2021-08-09T05:14:13.888797+00:00 app[web.1]:   File "<string>", line 11, in <module>
2021-08-09T05:14:13.888798+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/firebase_admin/__init__.py", line 71, in initialize_app
2021-08-09T05:14:13.888798+00:00 app[web.1]:     raise ValueError((
2021-08-09T05:14:13.888801+00:00 app[web.1]: ValueError: The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name.
2021-08-09T05:14:13.889714+00:00 app[web.1]: 10.41.181.68 - - [09/Aug/2021 05:14:13] "[35m[1mGET /start HTTP/1.1[0m" 500 -

**Comment by satish603** [comment]
resolved using meta tag
